name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.4'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.12.4'

    - name: Install Xvfb (Virtual Display)
      run: sudo apt-get install -y xvfb

    - name: Initialize Conda (shell configuration)
      shell: bash -l {0}
      run: |
        conda init bash
        source ~/.bashrc  # Reload the shell

    - name: Create and activate environment
      shell: bash -l {0}  # Ensure shell is reloaded
      run: |
        conda create --name test-env python=3.12.4 -y
        source ~/.bashrc  # Source again to ensure environment is available
        conda activate test-env

    - name: Install dependencies
      run: |
        conda activate test-env
        pip install -r requirements.txt

    - name: Run Program in CI Mode
      shell: bash -l {0}
      run: |
        conda activate test-env
        export GITHUB_ACTIONS=true
        Xvfb :99 &
        export DISPLAY=:99
        python -u main.py

    - name: Install Flake8
      run: |
        conda activate test-env
        conda install flake8 -y

    - name: Lint with flake8
      shell: bash -l {0}
      run: |
        conda activate test-env
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda activate test-env
        pytest
