name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12.4
      uses: actions/setup-python@v3
      with:
        python-version: '3.12.4'

    - name: Install Miniconda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-update-conda: true
        python-version: '3.12.4'

    - name: Initialize Conda
      run: |
        conda init bash
        source ~/.bashrc
        conda config --set always_yes yes --set changeps1 no
        conda info -a  # Useful for debugging any issues with conda

    - name: Activate base environment and install dependencies
      run: |
        conda activate base
        conda install --file requirements.txt

    - name: Run the program
      run: |
        python main.py

    - name: Lint with flake8
      run: |
        conda install flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install pytest
        pytest
